### ISSUE TITLE
Simply doesnt work

### ISSUE THREAD

**Issue by ghost** [morhogg/react-fitty#1]
Simply doesn't work.

https://codesandbox.io/s/brokenfitty-6rmuh?file=/src/App.js

**Comment by hexetia** [comment]
Thanks for the report with an example, I think I already found the problem

The wrapper div in ReactFitty component don't inherit the correct width when the parent is using display: flex, I will fix that and I will also add more test cases with other "display" properties

**Comment by hexetia** [comment]
can you please test this release: 1.0.1?

https://codesandbox.io/s/brokenfitty-forked-o5qe6 - with the release fix

**Comment by ghost** [comment]
Fixed! Thank you @morhogg 😄
