### ISSUE TITLE
Text Over-scaling

### ISSUE THREAD

**Issue by ghost** [morhogg/react-fitty#2]
When a fitty is nested, it causes the text to overscale and breaks container boundaries. This can't be fixed with maxSize.

https://codesandbox.io/s/brokenfittycentering-vn4ij?file=/src/App.js

**Comment by hexetia** [comment]
I'll investigate, thanks for reporting: P

**Comment by ghost** [comment]
I found the issue, it's just the auto line-height. If you shrink the line-height for each fitty to like .7 or depending on your font, it will remove this extra spacing above and below the text. It wasn't a bug, my apologies.
